package pojo;
// Generated Oct 11, 2022 1:20:50 PM by Hibernate Tools 4.3.1

import DAO.DAOAlbums;
import DAO.DAOOrders;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import javax.faces.bean.ManagedBean;

/**
 * Orders generated by hbm2java
 */

@ManagedBean
public class Orders  implements java.io.Serializable {


     private Integer idOrder;
     private Integer amount;
     private Integer price;
     private Integer totalPrice;
     private String idAlbum;
     private Integer idAdmin;
     private Date orderDate;

    public Orders() {
    }

    public Orders(Integer amount, Integer price, Integer totalPrice, String idAlbum, Integer idAdmin, Date orderDate) {
       this.amount = amount;
       this.price = price;
       this.totalPrice = totalPrice;
       this.idAlbum = idAlbum;
       this.idAdmin = idAdmin;
       this.orderDate = orderDate;
    }
   
    public Integer getIdOrder() {
        return this.idOrder;
    }
    
    public void setIdOrder(Integer idOrder) {
        this.idOrder = idOrder;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public Integer getTotalPrice() {
        return this.totalPrice;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public Integer getPrice() {
        return price;
    }
    
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getIdAlbum() {
        return this.idAlbum;
    }
    
    public void setIdAlbum(String idAlbum) {
        this.idAlbum = idAlbum;
    }
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }


     public void saveOrder(){
        DAOOrders order = new DAOOrders();
        order.addOrder(this);
    }
    
    public void deleteOrder(){
        DAOOrders order = new DAOOrders();
        order.deleteOrder(idOrder);
        amount = 0;
        price = 0;
        totalPrice = 0;
        idAdmin = 0;
        idAlbum = "";
    }
    
    public String getbyidAlbum(){
        String id = idAlbum.toString();
        DAOAlbums album = new DAOAlbums();
        List<Albums> lAlbum = album.getbyID(id);
        try {
            if (lAlbum != null) {
                price = lAlbum.get(0).price;
                idAlbum = lAlbum.get(0).idAlbum;
        return "order_form";
            }
        } catch (Exception e) {
            System.out.println(e);  
        }
        return "order_form_failed";
    }
    
    public List<Orders> getAllRecords(){
        DAOOrders order = new DAOOrders();
        List<Orders> lOrder = order.retrieveTblOrder();
        return lOrder;
    }
    
    public String updateOrder(){
        DAOOrders order = new DAOOrders();
        order.updateOrder(this);
        amount = 0;
        price = 0;
        totalPrice = 0;
        idAdmin = 0;
        idAlbum = "";
        return "order_list";
    }


}


